[package]
name = "bevy_ui_extras"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.2"}
glam = "0.24.1"
bevy_component_extras = "0.1.1"
bevy-inspector-egui = "0.19.0"
egui = "0.22.0"
bevy_egui = "0.21.0"
bevy_window = "0.11.2"

#[lib]
#crate-type=["lib"]