[package]
name = "bevy_ui_extras"
version = "0.5.0"
edition = "2021"
repository = "https://github.com/rydb/bevy_ui_extras"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "A crate containing a collection of utilities to make working with ui in bevy easier."

[dependencies]
bevy_ecs = { version = "0.13" }
bevy_utils = { version = "0.13" }
bevy_window = "0.13"


glam = "0.25"
bevy-inspector-egui =  {git = "https://github.com/jakobhellermann/bevy-inspector-egui", rev = "f0039054d3954b1dd7e51de73e7bbe432534d472"}
egui = "0.26"
bevy_egui = "0.25"

[dev-dependencies]
bevy = {version = "0.13", features = ["dynamic_linking"]}